version: '3.5'
services:
  node:
    container_name: docker-php-node
    image: docker.pkg.github.com/tommyheavenly7/docker-node/node12:latest
    volumes:
      - "./:/var/project:delegated"
      - "node-dependencies:/var/project/node_modules"
      - "./docker/.volumes/npm:/root/.npm:delegated"
    working_dir: /var/project
    entrypoint: ["/usr/local/bin/node"]

volumes:
  node-dependencies: