###
## tommynovember7/php71-fpm
###

FROM php:7.1-fpm-stretch

<%- include('../../_partial/execute_apt-get') %>

<%- include('../../_partial/install_gs') %>

<%- include('../../_partial/install_convert') %>

<%- include('../../_partial/install_node') %>

<%- include('../../_partial/install_aws-cli') %>

<%- include('../../_partial/install_php-modules') %>

<%- include('../../_partial/install_mcrypt-module') %>

<%- include('../../_partial/execute_cleanup') %>

<%- include('../../_partial/install_tests') %>